name: feat_main
description: Main feature for Flutter Bit Beat
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  lib_base:
    path: ../lib_base
  lib_uikit:
    path: ../lib_uikit
  service_router:
    path: ../service_router
  service_core:
    path: ../service_core
  feat_home:
    path: ../feat_home
  feat_trade:
    path: ../feat_trade
  feat_market:
    path: ../feat_market
  feat_favorites:
    path: ../feat_favorites
  feat_wallet:
    path: ../feat_wallet
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/light/
    - assets/images/dark/
    - assets/images/svg/common/
    - assets/images/svg/light/
    - assets/images/svg/dark/