name: lib_base
description: Base library for Flutter Bit Beat
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  hive: ^2.2.3
  pretty_dio_logger: 1.3.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  package_info_plus: ^8.0.0
  device_info_plus: ^12.3.0
  connectivity_plus: ^7.0.0
  encrypt: ^5.0.3
  crypto: 3.0.3
  logger: ^1.1.0 # Added as safe default
  flutter_easyloading: 3.0.5 # Used in CommonController probably
  easy_refresh: ^3.4.0
  web_socket_channel: ^3.0.3
  equatable: ^2.0.8
  rxdart: ^0.28.0
  synchronized: ^3.4.0



